version: '3.3'
services:
  mysql-test-db:
    image: mysql:5.7
    restart: always
    container_name: mysql-test-db
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - custom-network
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-test-db-volumes:/var/lib/mysql
volumes:
  mysql-test-db:
networks:
  custom-network:
    driver: bridge