version: '3.3'
services:
  mysql-test-db:
    image: mysql:5.7
    restart: always
    container_name: mysql-test-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./scripts/mysqlinit.sql:/docker-entrypoint-initdb.d/1.sql"
      - ./volume-mysql-test-db:/var/lib/mysql
volumes:
  mysql-test-db: